version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80085:80"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm run dev
